services:
  invilensData1:
    container_name: invilens_postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: invilensdb
    volumes:
      - invilensData1:/var/lib/postgres/data
    ports:
      - 5433:5432

  invilensMongodb:
    container_name: invilens_mongodb
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - invilensMongodb:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=umair
      - MONGO_INITDB_ROOT_PASSWORD=umair

  invilensMongo-express:
    container_name: invilens_mongo_express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=umair
      - ME_CONFIG_MONGODB_ADMINPASSWORD=umair
      - ME_CONFIG_MONGODB_SERVER=invilensMongodb


  kafka:
    image: apache/kafka
    container_name: kafka
    ports:
      - "9092:9092"

volumes:
  invilensData1:
    driver: local
  invilensPgadmin:
    driver: local
  invilensMongodb:
    driver: local